FROM ubuntu:latest

run sudo apt-get -y install software-properties-common && \
    sudo add-apt-repository -y ppa:fkrull/deadsnakes && \
    sudo apt-get -q -y update && \
    sudo apt-get install -y python2.7 && \
    sudo ln -s /usr/bin/python2.7 /usr/bin/python && \
    sudo apt-get install -y curl python-setuptools python-pip python-dev python-protobuf






