#!/bin/bash
#Run go in Docker container for the current user

U=$USER
N=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`
I=$UID
P=`pwd`
C=$1
docker run -it --rm -v /home/$U:/home/$U asterkin/golang go-run $U "$N" $I $P $C



