#!/bin/bash

#Prepare mesos slave image
#Pre-requisite: none
#Arguments: none
#Post-processing: take snapshot, create a fresh instance, run mesos-slave-config

sudo yum -y update

#Docker
sudo tee /etc/yum.repos.d/docker.repo <<-'EOF'
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF
sudo yum -y install docker-engine
sudo service docker start
sudo chkconfig docker on
sudo usermod -aG docker $USER

#Mesos
sudo rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
sudo yum -y install mesos
sudo systemctl stop mesos-master.service
sudo systemctl disable mesos-master.service

