#!/bin/bash

#Run one of the chol system scripts
wget -O /tmp/$1 https://github.com/asterkin/chol/raw/master/system/$1
chmod +x /tmp/$1
if [ "$#" -gt 1 ]; then
ARGS="${@:2}"
else
ARGS=""
fi
/tmp/$1 "$ARGS"
rm /tmp/$1


