#!/bin/bash

#Run one of the chol system scripts
cmd=$1
shift
whitespace="[[:space:]]"
args=/tmp/$cmd
for arg in "$@";
do
  if [[ $arg =~ $whitespace ]]
  then
    arg=\"$arg\"
  fi
  args="$args $arg"
done
wget -q -O /tmp/$cmd https://github.com/asterkin/chol/raw/master/system/$cmd
chmod +x /tmp/$cmd
echo "$args"
eval "$args"
rm /tmp/$cmd


