#!/bin/bash
#Configure git to be able to commit changes
#Usage: git-config <email-server>
#Pre-requisites: git installed
#TODO: currently restricted to using the same user name for e-mail. 
#TODO:  good enough for corporate usage

NAME=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`
git config --global --add user.name "$NAME"
git config --global --add user.email "$USER@$1"
git config --global --list

