#!/bin/bash
#Installs the most recent version of Gradle build system
#Pre-requsite: jdk (e.g. oracle-jdk8-install)

sudo add-apt-repository -y ppa:cwchien/gradle
sudo apt-get -q -y update
sudo apt-get -y install gradle

