#!/bin/bash
# Installs oracle jdk version 8
# Pre-requisites: none

sudo apt-get -y install python-software-properties
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get -q -y update
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-get -y install oracle-java8-installer
sudo ln -f -s /usr/lib/jvm/java-8-oracle /usr/lib/jvm/default-java
#Ensure RAM-disk copy of jvm on every boot (not ideal, since it conflict with other configrations)
sudo cat >/etc/rc.local <<EOF
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# Make a copy of jvm on RAM-disk to improve Eclipse preformance.
mkdir /dev/shm/java
cp -r /usr/lib/jvm/java-8-oracle/* /dev/shm/java
exit 0
EOF

sudo reboot

