#!/bin/bash

#Installs mesos slave image
#Pre-requisite: none

# Setup
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

# Add the repository
echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | \
  sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update

sudo apt-get -y install mesos

sudo apt-get install -y curl
curl -s https://get.docker.io/ubuntu/ | sudo sh

cp ./mesos-slave-config ~/


