#!/bin/bash

#Configure mesos master image
#Pre-requisite: floating IPs are allocated manualy; mesos installed in image
#Arguments: <cluster name> <server id> <master 1 floating ip> <master 2 floating ip>
#Post-processing: folating IPs should be associated manually

sudo sed "s/localhost/localhost `hostname`/" -i /etc/hosts

# Setup
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

# Add the repository
echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | \
sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update

sudo apt-get -y install mesos marathon

sudo sh -c "echo $2 > /etc/zookeeper/conf/myid"
sudo sed "s/#server.1=zookeeper1/server.1=$3/" -i /etc/zookeeper/conf/zoo.cfg
sudo sed "s/#server.2=zookeeper2/server.2=$4/" -i /etc/zookeeper/conf/zoo.cfg
sudo service zookeeper restart

sudo sed "s/localhost/$3,$4/" -i /etc/mesos/zk
sudo sh -c "echo '1' >/etc/mesos-master/quorum"
sudo sh -c "echo $HOST_IP >/etc/mesos-master/ip"
sudo sh -c "echo MesosCluster >/etc/mesos-master/cluster"
sudo sh -c "echo $HOST_IP >/etc/mesos-master/hostname"
sudo service mesos-master restart

sudo service mesos-slave stop
sudo sh -c "echo manual > /etc/init/mesos-slave.override"

sudo mkdir /etc/marathon/conf
sudo sh -c "echo $HOST_IP >/etc/marathon/conf/hostname"
sudo service marathon restart



