#!/bin/bash

#Install scla-ide (Eclipse)run script and desktop shortcut
#Pre-requisites: git and docker installed

docker pull asterkin/scala-ide
git clone http://github.com/asterkin/chol
cd chol/scala-ide
./install
cd
rm -rf chol
