#!/bin/bash

sudo dnf install -y golang
export GOPATH=/home/$USER/gotools
go get -u github.com/nsf/gocode
go get -u golang.org/x/tools/cmd/guru
go get -u github.com/rogpeppe/godef
echo 'export GOPATH=/home/$USER/gotools' >> ~/.bashrc
echo 'export PATH=$GOPATH/bin:$PATH' >> ~/.bashrc
cd /tmp
wget http://eclipse.bluemix.net/packages/neon/data/eclipse-inst-linux64.tar.gz
tar xzvf eclipse-inst-linux64.tar.gz
sudo eclipse-installer/eclipse-inst



