#!/bin/bash

#Configure proper user for git 
#Usage:  set-git e-mail
#Pre-requisites: git installed 

if [ "$#" -ne 1 ]; then
    echo "Usage: set-git e-mail"
    exit 1 
fi
NAME=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`
EMAIL_SERVER=$1.com
git config --global --add user.name "$NAME"
git config --global --add user.email "$USER@$EMAIL_SERVER"
git config --global --list


