#!/bin/bash
#Run sbt in Docker container for the current user

U=$USER
N=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`
I=$UID
A=$1
P=`pwd`
docker run -i --rm -e DISPLAY=$DISPLAY -v /home/$U:/home/$U chol/eclipse <<EOF
sudo adduser --disabled-password --no-create-home --gecos "$N" --uid $I $U
su $U
cd 
eclipse
EOF


