#!/bin/bash

U=$USER
N=`getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1`
I=$UID
P=`pwd`
C="$@"
docker run -ti --rm \
	-v /home/$U:/home/$U \
	--env OS_USERNAME="$OS_USERNAME"     \
	--env OS_PASSWORD="$OS_PASSWORD" \
	--env OS_TENANT_ID="$OS_TENANT_ID" \
	--env OS_TENANT_NAME="$OS_TENANT_NAME" \
	--env OS_AUTH_URL="$OS_AUTH_URL" \
	--env HEAT_URL="$HEAT_URL" \
	asterkin/heatclient heat-run $U "$N" $I $P "$C"
  
