FROM ubuntu:latest

run sudo apt-get -y install software-properties-common && \
    sudo add-apt-repository -y ppa:ansible/ansible && \
    sudo apt-get -q -y update && \
    sudo apt-get install -y ansible



